# Feature Extraction — Core Types

Feature Extraction converts raw data into numerical form so that machine learning models can understand it.

## Why Feature Extraction is Important?

- Machine learning models cannot understand raw data like text or categories
- It improves model accuracy
- Reduces noise and irrelevant information
- Helps in faster training

## 1. Numerical Features

Numerical features are numbers like age, salary, marks, etc.

Why we use transformation?
- To make values comparable
- To improve model performance

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

data = pd.DataFrame({'salary':[10000,20000,30000]})

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

scaled_data

array([[-1.22474487],
       [ 0.        ],
       [ 1.22474487]])

## 2. Categorical Features

Categorical data contains text values like city, gender, category.

Why?
- Machine learning models cannot understand text
- So we convert it into numbers

In [2]:
from sklearn.preprocessing import OneHotEncoder

data = [['Pune'], ['Mumbai'], ['Delhi']]

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(data)

encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

## 3. Text Features

Text data includes reviews, messages, comments.

Why?
- Models cannot understand sentences
- So we convert text into numbers

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

texts = ["I love AI", "AI is future"]

vectorizer = CountVectorizer()
text_features = vectorizer.fit_transform(texts)

text_features.toarray()

array([[1, 0, 0, 1],
       [1, 1, 1, 0]])

## 4. DateTime Features

Date and time data must be converted into parts.

Example:
- Year
- Month
- Day

Why?
- Raw date is not useful for models

In [4]:
import pandas as pd

df = pd.DataFrame({'date': pd.to_datetime(['2024-01-01'])})

df['month'] = df['date'].dt.month

df

,date,month
0,2024-01-01,1


## 5. Dimensionality Reduction

Reduces number of features while keeping important information.

Why?
- Too many features slow down model
- Can cause overfitting

In [5]:
from sklearn.decomposition import PCA
import numpy as np

X = np.random.rand(5,3)

pca = PCA(n_components=2)
reduced = pca.fit_transform(X)

reduced

array([[ 0.32247674,  0.37518658],
       [-0.3182321 , -0.28595243],
       [-0.23755443,  0.16635734],
       [ 0.66338895, -0.25825521],
       [-0.43007916,  0.00266372]])

## Summary

There are 5 main types of Feature Extraction:

1. Numerical → scaling numbers  
2. Categorical → convert text to numbers  
3. Text → convert sentences to numbers  
4. DateTime → extract parts from date  
5. Dimensionality Reduction → reduce features  

These are the foundation of Machine Learning preprocessing.

## Numerical Feature Subtypes

These are techniques used to improve numerical data.

### 1. Scaling

Why?
- Different features have different ranges
- Helps models like KNN, SVM

Types:
- StandardScaler → mean = 0
- MinMaxScaler → range (0,1)

In [6]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd

data = pd.DataFrame({'value':[10,20,30]})

StandardScaler().fit_transform(data)
MinMaxScaler().fit_transform(data)

array([[0. ],
       [0.5],
       [1. ]])

### 2. Binning

Why?
- Converts continuous → categories
- Helps in non-linear data

In [7]:
import pandas as pd

data = pd.DataFrame({'value':[100,500,1000]})
data['bin'] = pd.cut(data['value'], bins=3)
data

,value,bin
0,100,"(99.1, 400.0]"
1,500,"(400.0, 700.0]"
2,1000,"(700.0, 1000.0]"


### 3. Polynomial Features

Why?
- Helps model learn relationships (x², x*y)

In [8]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
poly.fit_transform([[2,3]])

array([[1., 2., 3., 4., 6., 9.]])

## Categorical Feature Subtypes

### 1. Label Encoding

Why?
- Converts text → numbers

Risk:
- Model may assume order

In [9]:
from sklearn.preprocessing import LabelEncoder

LabelEncoder().fit_transform(['A','B','C'])

array([0, 1, 2])

### 2. One-Hot Encoding

Why?
- No false ordering
- Most used

In [10]:
from sklearn.preprocessing import OneHotEncoder

OneHotEncoder(sparse_output=False).fit_transform([['A'],['B']])

array([[1., 0.],
       [0., 1.]])

### 3. Target Encoding

Why?
- Useful for high categories

Note:
- Can cause data leakage

In [11]:
import pandas as pd

df = pd.DataFrame({'cat':['A','B','A'],'label':[1,0,1]})
df['encoded'] = df.groupby('cat')['label'].transform('mean')
df

,cat,label,encoded
0,A,1,1.0
1,B,0,0.0
2,A,1,1.0


### 4. Feature Hashing

Why?
- Used when too many categories

In [12]:
from sklearn.feature_extraction import FeatureHasher

hasher = FeatureHasher(n_features=4, input_type='string')
hasher.transform([['city1'],['city2']]).toarray()

array([[ 1.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.]])

## Text Feature Subtypes

### 1. Bag of Words

Why?
- Counts words

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

CountVectorizer().fit_transform(["hello world"]).toarray()

array([[1, 1]])

### 2. TF-IDF

Why?
- Gives importance to important words

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

TfidfVectorizer().fit_transform(["hello world"]).toarray()

array([[0.70710678, 0.70710678]])

### 3. N-grams

Why?
- Captures phrases

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

CountVectorizer(ngram_range=(1,2)).fit_transform(["hello world"]).toarray()

array([[1, 1, 1]])

## DateTime Feature Subtypes

### 1. Extract Components

Why?
- Date itself not useful

In [16]:
import pandas as pd

df = pd.DataFrame({'date': pd.to_datetime(['2024-01-01'])})
df['month'] = df['date'].dt.month
df

,date,month
0,2024-01-01,1


### 2. Cyclical Encoding

Why?
- Month is circular (Dec close to Jan)

In [17]:
import numpy as np

month = 1
np.sin(2*np.pi*month/12)

np.float64(0.49999999999999994)

## PCA

Why?
- Reduce features
- Keep important info

In [18]:
from sklearn.decomposition import PCA
import numpy as np

PCA(n_components=2).fit_transform(np.random.rand(5,3))

array([[ 0.45772861, -0.25077115],
       [-0.4700379 , -0.05117018],
       [ 0.1226515 ,  0.18700342],
       [-0.16760322, -0.27223315],
       [ 0.05726101,  0.38717106]])

## What is Pipeline?

Pipeline = sequence of steps

Example:
Data → Scaling → Encoding → Model

Why?
- Clean code
- No data leakage
- Used in real projects

In [19]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
])

pipe

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('scaler', ...), ('model', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not wo

## ColumnTransformer

Used when different columns need different processing.

Example:
- Numerical → scaling
- Categorical → encoding

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), ['age']),
    ('cat', OneHotEncoder(), ['city'])
])