14 January 2026

NumPy Library

Lesson 1: Introduction

What is NumPy?
  - NumPy is a Python library used for working with arrays.
  - It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

Why NumPy was created?
  -  In Python we have lists that serve the purpose of arrays, but they are slow to process.
  -  NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
  -  The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
  - Arrays are very frequently used in data science, where speed and resources are very important.

In [35]:
import numpy as np 
print(np.array([1,2,3]))

[1 2 3]


In [36]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [37]:
import numpy as np 
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

0-D Arrays:
 - 0-D arrays, or Scalar, are the elements in an array. Each valu in an array is a 0-D array.

In [38]:
# 0-D array example

import numpy as np

arr = np.array(44)

print(arr)

44


1-D Array:
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

- These are the most common and basic arrays.

In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2-D Array:
 - An array that has 1-D arrays as its elements is called a 2-D array.
 - These are often used to represent matrix or 2nd order tensors.

 <!-- NumPy has a whole sub module dedicated towards matrix operations called numpy.mat -->

In [40]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


3-D Arrays:
 - An array that has 2-D arrays (matrices) as its elements is called 3-D array.
 - These are often used to represent a 3rd order tensor.

In [41]:
import numpy as np

arr = np.array([[[1,2,3,], [4,5,6]], [[7,8,9],[10,11,12]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


NumPy Arrays provides the ndim attribute that returns an integer that tells us howmany dimentions the arrays have:

In [42]:
# Checking number of dimentions

import numpy as np

a = np.array(22)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6,]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher dimentional Array:

- An array can have any number of dimentions.
- When the array is created, you can define the number of dimentions by using the ndim argument.


In [43]:
# Creating an array with 5 dimentions and verify that it has 5 dimentions

import numpy as np

arr = np.array([1,2,3,4], ndmin = 5)

print(arr)
print("Number of dimentions: ",arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimentions:  5


NumPy Array Indexing

Access Array Elements:
 - Array indexing is the same as accessing an array element.
 - You can access an array element by referring to its index number.
 - The indexing in NumPy arrays start with 0,meaning that the first element has index 0, and the second inde 1 etc.

In [44]:
#  Get the first element

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [45]:
#  Get the second element from the following array.

import numpy as np

arr = np.array([1,2,3,4])

print(arr[1])

2


In [46]:
# Get the third and fourth elements from the following array and add them.

import numpy as np

arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7


Access 2-D Arrays
 - To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

 - Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [47]:
# Example 
# Access the element on the first row, second column:

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("2nd element on 1st row: ", arr[0,1])

2nd element on 1st row:  2


In [48]:
#  Access the element on the 2nd row, 5th column:

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("5th element on 2nd row: ", arr[1,4])


5th element on 2nd row:  10


Access 3-D Arrays
 - To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [49]:
# Access the third element of the second array of the first array

import numpy as np

arr = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])

print(arr[0, 1, 2])

6


Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

NEGATIVE INDEXING
 - print the last element from the 2nd dim:

In [50]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print("Last element from 2nd dim: ", arr[1, -1])

Last element from 2nd dim:  10


Slicing arrays
  - Slicing in python means taking elements from one given index to another given index.
  - We pass slice instead of index like this: [start:end].
  - We can also define the step, like this: [start:end:step].
  - If we don't pass start its considered 0
  - If we don't pass end its considered length of array in that dimension
  - If we don't pass step its considered 1

In [51]:
# slice elements from index 5 from the following array

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [52]:
# slice elements from the beginning to index 4 (not included):

import numpy as np

arr  = np.array([1,2,3,4,5,6,7])

print(arr[:4])

[1 2 3 4]


Negative slicing
 - use the minus operator to refer to an index 1 from the end.

In [53]:
# slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])

[5 6]


STEP:
  - Use the step value to determine the step of the slicing:

In [54]:
# Return every other element from index 1 to index 5:

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [55]:
#  Return every other element from the entire array:

arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])

[1 3 5 7]


SLICING 2-D ARRAYS

In [56]:
# from the second element, slice elements from index 1 to index 4(not included):

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, 1:4])

[7 8 9]


In [58]:
# from both elements, return index 2:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0:2,2])

[3 8]


In [59]:
# from both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
